---
- name: Populate openstack username,password and url
  set_fact:
      config_file: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"

- name: Include openstack creds
  ansible.builtin.include_vars: "{{ config_file }}"

- name: install correct version of openstacksdk
  ansible.builtin.pip:
        name: 
           - openstacksdk>=1.0.0
           - openstackclient
  delegate_to: localhost

- name: "Get the image list"
  openstack.cloud.image_info:
  register: imagelist

- name: "set variable for image list which should be owned by {{ owner_project }}"
  ansible.builtin.set_fact:
        admin_owned_images: "{{ imagelist.images | rejectattr('name','search','^cert-*|^pe[0-9]*|^ex[0-9]*')| map(attribute='id') }}"

- name: Change ownership of images owned by admin
  #ansible.builtin.shell: "openstack image set --project {{ owner_project }} {{ item }}"
  ansible.builtin.shell: openstack image show 6df863ce-59b2-4c8f-bf28-c09d45d49645 -c owner
  #delegate_to: localhost
  environment: 
      OS_USERNAME: "{{ clouds.devstack.auth.username }}"
      OS_PASSWORD: "{{ clouds.devstack.auth.password }}"
      OS_PROJECT_NAME: "{{ clouds.devstack.auth.project_name }}"
      OS_AUTH_URL: "{{ clouds.devstack.auth.auth_url }}"
      OS_USER_DOMAIN_NAME: Default
      OS_PROJECT_DOMAIN_NAME: Default
  #loop: "{{ admin_owned_images }}"

     

