---
- name: Populate openstack username,password and url
  set_fact:
      config_file: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"

- name: Include openstack creds
  ansible.builtin.include_vars: "{{ config_file }}"

- name: install correct version of openstacksdk
  ansible.builtin.pip:
        name: 
           - openstacksdk>=1.0.0
           - openstackclient
  delegate_to: localhost

#- name: install openstackclient rpm
#  ansible.builtin.yum:
#    name: python3-openstackclient
#    state: latest
#  delegate_to: localhost

- name: "Get the image list"
  openstack.cloud.image_info:
  register: imagelist

- name: "set variable for image list which should be owned by {{ owner_project }}"
  ansible.builtin.set_fact:
        admin_owned_images: "{{ imagelist.images | rejectattr('name','search','^cert-*|^pe[0-9]*|^ex[0-9]*')| map(attribute='id') }}"

- name: print
  ansible.builtin.debug: 
        msg: "{{ config_file }}"

- name: Change ownership of images owned by admin
  #ansible.builtin.shell: "openstack image set --project {{ owner_project }} {{ item }}"
  ansible.builtin.shell: "openstack image show 6df863ce-59b2-4c8f-bf28-c09d45d49645 -c owner"
  environment: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"
   #   OS_USERNAME: "{{ user }}"
   #   OS_PASSWORD: "{{ passwd }}"
   #   OS_PROJECT_NAME: "{{ os_project }}"
   #   OS_AUTH_URL: "{{ url }}"
   #   OS_USER_DOMAIN_NAME: Default
   #   OS_PROJECT_DOMAIN_NAME: Default
  #loop: "{{ admin_owned_images }}"

     

