---
# defaults file for find-orphaned-images
cluster_name: "{{ cluster }}"
dc: "{{ region }}"
cloud_name: "{{ cluster_name }}-{{ dc }}"
vault_folder: "overcloud/{{ cloud_name }}"
git_secret_folder: 'common/git/RedHatTraining'
vault_file: vault_config.yaml
repo_dir: '/tmp/ole-config-labenv'
git_heatdir: "{{ repo_dir }}/data/zdoc/osp_heat_template"   
exclusion_list: '^[Ee][Xx][0-9][0-9][0-9]|^[Pp][Ee][0-9][0-9][0-9]|^cert-|rhcos|mirror|OCP-client-install|ocp|^rhel-|^octavia-|^cirros-|^sidecar$|tsunami|^node2$|^dle-|^ole-'
file1: '/tmp/git-secret'
file2: '/tmp/cloud-image-list'
file3: '/tmp/heat-template-image-list'
file4: '/tmp/cloud-image-list-final'
file5: '/tmp/final-list'
