- name: find orphaned images test
  hosts: localhost
  collections:
    - openstack.cloud
    - community.hashi_vault
  tasks:
    - name: call role
      include_role:
        name: find-orphaned-images
