---
- name: Populate openstack username,password and url etc
  set_fact:
      config_file: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"

- name: Include all collected openstack variables
  ansible.builtin.include_vars: "{{ config_file }}"

- name: Install correct version of openstacksdk and install openstackclient
  ansible.builtin.pip:
        name: 
           - openstacksdk>=1.0.0
           - openstackclient

- name: Get the image list
  openstack.cloud.image_info:
  register: imagelist

- name: Get {{ owner_project }} id
  openstack.cloud.project_info:
        name: "{{ owner_project }}"
  register: owner_project_details

- name: "Set variable for: image list which should be owned by {{ owner_project }} , {{ owner_project }} id"
  ansible.builtin.set_fact:
        images_no_ownerhip_change: "{{ imagelist.images | rejectattr('name','search','^cert-*|^pe[0-9]*|^ex[0-9]*|.-rhcos$') }}"
        new_project_owner_id: "{{ owner_project_details.projects[0]['id'] }}"

- name: "Set variable for image names/ids owned by other owners rather than {{ owner_project }}"
  ansible.builtin.set_fact:
        image_name_ownership_change: "{{ images_no_ownerhip_change | rejectattr('owner','search',new_project_owner_id)| map(attribute='name') }}"
        image_id_ownership_change: "{{ images_no_ownerhip_change | rejectattr('owner','search',new_project_owner_id)| map(attribute='id') }}"

- name: Create folder for storing the file of image list
  ansible.builtin.file:
        name: "{{ dump_file_folder }}"
        state: directory
        mode: '0755' 

- name: "Dump the image list in file {{ dump_file }} of {{ dump_host }} (even if list is empty)"
  ansible.builtin.shell: echo {{ image_name_ownership_change | join(',') }} | tr ',' '\n' > {{ dump_file }}
  when: image_id_ownership_change | length != 0

- name: "Dump the image list in file {{ dump_file }} of {{ dump_host }} (even if list is empty)"
  ansible.builtin.lineinfile: 
        path: "{{ dump_file }}"
        state: absent
  when: image_id_ownership_change | length == 0

- name: "Change ownership of images to {{ owner_project }} project (if there is any)"
  ansible.builtin.shell: "openstack image set --project {{ owner_project }} {{ item }}"
  environment: 
      OS_USERNAME: "{{ clouds.devstack.auth.username }}"
      OS_PASSWORD: "{{ clouds.devstack.auth.password }}"
      OS_PROJECT_NAME: "{{ clouds.devstack.auth.project_name }}"
      OS_AUTH_URL: "{{ clouds.devstack.auth.auth_url }}"
      OS_USER_DOMAIN_NAME: Default
      OS_PROJECT_DOMAIN_NAME: Default
  loop: "{{ image_id_ownership_change }}"
